on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: install sbt
        uses: sbt/setup-sbt@v1
      - name: build
        run: sbt fastLinkJS
      - name: predeploy
        run: |
          mkdir pub
          mkdir pub/hw-fastopt
          cp target/scala-2.12/classes/index.html pub/
          cp target/scala-2.12/hw-fastopt/main.js pub/hw-fastopt/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pub
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5